# version format
version: 0.2.5-{build}

# pull request template
pull_requests:
  do_not_increment_build_number: true

# vm template
image: Visual Studio 2022

# install dependencies
install:
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init --recursive

# build step
build_script:
  - dotnet build

# success/failure tracking
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL